### ISSUE TITLE
null is not an object (evaluating 'this.left.executeOnEveryNode')

### ISSUE THREAD

**Issue by Boubaker93** [antoniopresto/react-native-local-mongodb#51]
## Bug Report
Hello, I'm getting this error `com.facebook.react.common.JavascriptException: null is not an object (evaluating 'this.left.executeOnEveryNode')` on my production app, specially in Galaxy S7 Edge android 7.0
Here is a stacktrace of the error : 

```
Fatal Exception: com.facebook.react.common.JavascriptException: null is not an object (evaluating 'this.left.executeOnEveryNode'), stack:
  at executeOnEveryNode (./s/binary-search-tree/lib/bst.js:509:29)
  at fn (./s/binary-search-tree/lib/bst.js:511:50)
  at fn (./s/binary-search-tree/lib/bst.js:511:50)
  at fn (./s/binary-search-tree/lib/bst.js:511:50)
  at fn (./s/binary-search-tree/lib/bst.js:511:50)
  at this (./s/binary-search-tree/lib/avltree.js:449:31)
  at ./s/react-native-local-mongodb/lib/indexes.js:303:31
  at getAll (./s/react-native-local-mongodb/lib/datastore.js:109:26)
  at getAllData (./s/react-native-local-mongodb/lib/datastore.js:339:27)
  at arguments (./s/react-native-local-mongodb/node_modules/async/lib/async.js:582:45)
  at wrapIterator (./s/react-native-local-mongodb/node_modules/async/lib/async.js:503:8)
  at apply (./s/react-native/Libraries/Core/Timers/JSTimers.js:298:17)
  at callback (./s/react-native/Libraries/Core/Timers/JSTimers.js:152:6)
  at passImmediates (./s/react-native/Libraries/Core/Timers/JSTimers.js:200:17)
  at _callImmediatesPass (./s/react-native/Libraries/Core/Timers/JSTimers.js:473:11)
  at _eventLoopStartTime (./s/react-native/Libraries/BatchedBridge/MessageQueue.js:344:9)
  at ./s/react-native/Libraries/BatchedBridge/MessageQueue.js:140:37
  at DebuggerInternal (./s/react-native/Libraries/BatchedBridge/MessageQueue.js:329:13)
  at ./s/react-native/Libraries/BatchedBridge/MessageQueue.js:140:37
  at ./s/react-native/Libraries/BatchedBridge/MessageQueue.js:118:17
```
I think the error is from the asyn library (v 0.2.10) and to fix it maybe update the library to the latest version (2.6.2)

## Environment
react: 16.6.3 
react-native: 0.58.5
react-native-local-mongodb: 2.2.5

**Comment by antoniopresto** [comment]
Hi, @Boubaker93.
could you test and give me feedback on version 3.0.0?
